import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

const config = [
  {
    // next-env.d.ts is generated by Next on every build and is not ours to lint.
    ignores: [
      ".next/**",
      "node_modules/**",
      "out/**",
      "data/**",
      "next-env.d.ts",
      // Local agent tooling state, not part of the site.
      ".gm/**",
      ".agentplug-kv/**",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    rules: {
      // Allow the `const { x: _x, ...rest }` idiom used to drop a field.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", ignoreRestSiblings: true },
      ],
    },
  },
];

export default config;
